### ISSUE TITLE
Fancy 404 error page

### ISSUE THREAD

**Issue by Tim-P** [jfrimmel/FriServer#6]
A good looking page for an occured error 404 instead of the regular browser-created page would be nice.

**Comment by jfrimmel** [comment]
I agree.
A possible implementation could look like this:
```Python
if not self._page_exists(requested_page):
    path = self.file_base_path + self.FILE_404
    if self._page_exists(path)
        response = self._send_file(path)
        sock._send_bytes(response)
    else:
        sock._send_bytes(self._http_response_code(404))
```
(code won't work)

This requires of course a, in your terms, 'fancy' page that mentions the fact, that the requested page is unavailable.

**Comment by jfrimmel** [comment]
This enhancement is added in commit `19a1a739a543d8ee521ef8ee06c13472e23271e0`.
